version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
      - run: aws configure set aws_secret_access_key ${AWS_ACCESS_SECRET}
      - run: aws configure set aws_region ${AWS_REGION_NAME}
#      - aws-cli/setup:
#          aws-access-key-id: AWS_ACCESS_KEY
#          aws-secret-access-key: AWS_ACCESS_SECRET
#          aws-region: AWS_REGION_NAME
      - run: aws --version
      - run: aws iam list-users
      - run:
          name: Create Cloudformation Stack
          command: | 
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
      - run: aws ec2 describe-instances
workflows:
  my-infra-workflows:
    jobs:
      - create_infrastructure
#          context: aws
#          context: aws