version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws --version
      - run: aws iam list-users
      - run:
          name: Create Cloudformation Stack
          command: | 
          aws cloudformation deploy \
            --template-file template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1
      - run: aws ec2 describe-instances
#      - aws-cli/setup:
#          aws-access-key-id: AWS_ACCESS_KEY
#          aws-secret-access-key: AWS_ACCESS_SECRET
#          aws-region: AWS_REGION_NAME

workflows:
  my-infra-workflows:
    jobs:
      - create_infrastructure:
#          context: aws